# Generated by Django 3.2.4 on 2021-06-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('num', models.IntegerField(blank=True, default=100, null=True)),
                ('prix_installation', models.FloatField(blank=True, default=0, null=True)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('prix_location', models.FloatField(blank=True, default=0, null=True)),
                ('date_debut_location', models.DateField(blank=True, null=True)),
                ('date_fin_location', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('num', models.IntegerField(blank=True, default=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Entreprise', max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('construction_site_name', models.CharField(max_length=200, null=True)),
                ('construction_site_adress', models.CharField(max_length=200, null=True)),
                ('construction_site_zip_code', models.IntegerField(default=0, null=True)),
                ('construction_site_city', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Work in Progress', 'Work in Progress'), ('Sended to Customer', 'Sended to Customer'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('adress', models.CharField(max_length=200, null=True)),
                ('zip_code', models.IntegerField(default=0, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(default=0, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_installation', models.FloatField(blank=True, default=0, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scaffolding.article')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scaffolding.offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='article',
            field=models.ManyToManyField(through='scaffolding.Offer_article', to='scaffolding.Article'),
        ),
        migrations.AddField(
            model_name='offer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scaffolding.customer'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('adress', models.CharField(max_length=200, null=True)),
                ('zip_code', models.IntegerField(default=0, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(default=0, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scaffolding.customer')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scaffolding.category_article'),
        ),
    ]
