# Generated by Django 3.2.4 on 2021-06-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffolding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_article',
            name='prix_installation',
        ),
        migrations.AddField(
            model_name='offer_article',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
